exclude: |
     (?xi)(^conda.recipe/meta.yaml|.*\.(csv|s[0-9]+p|mdf|cti|ts|svg))
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-yaml

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.2.2'
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
